//login
const REGISTER_POST_SUCCESS = 'register/postSuccess'
const LOGIN_POST_SUCCESS = 'login/postSuccess'

// fetch repo
const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';

// add repo
const ADD_REPO_SUCCESS = 'ADD_REPO_SUCCESS';
const ADD_REPO_FAILURE = 'ADD_REPO_FAILURE';

// fetch task
const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

export {
   REGISTER_POST_SUCCESS,
   LOGIN_POST_SUCCESS,
   FETCH_REPOS_SUCCESS,
   FETCH_REPOS_FAILURE,
   ADD_REPO_SUCCESS,
   ADD_REPO_FAILURE,
   GET_TASKS_REQUEST,
   GET_TASKS_SUCCESS,
   GET_TASKS_FAILURE
}
