const REGISTER_POST_SUCCESS = 'register/postSuccess'

// fetch repo
const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';

export { REGISTER_POST_SUCCESS, FETCH_REPOS_SUCCESS, FETCH_REPOS_FAILURE }